name: build
on: push

jobs:
  aah:
    runs-on: ubuntu-latest

    steps:
      # 1) Clona el repo
      - uses: actions/checkout@v4

      # 2) Java 8 (es lo que el proyecto necesita)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3) SDK de Android (acción estable: futureware-tech)
      - uses: futureware-tech/android-sdk@v1
        with:
          components: |
            platform-tools
            build-tools;29.0.3
            platforms;android-29

      # 4) Compila el APK debug
      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon

      # 5) Sube el artefacto
      - uses: actions/upload-artifact@v4
        with:
          name: aah-apk
          path: app/build/outputs/apk/debug/app-debug.apk
